[package]
name = "progress_bar"
version = "0.1.0"
authors = ["wyp"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
indicatif = {version = "0.15.0", features = ["rayon"]}
rayon = "1.4.1"
console = "0.12.0"
